apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  labels:
    app: portfolio
spec:
  type: LoadBalancer
  selector:
    app: portfolio
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
